export const COLORS = [
  "#156E84",
  "#7F608F",
  "#AE4F46",
  "#CD8880",
  "#A39547",
  "#CFC99D",
  "#3AAE61",
  "#96D6AB",
  "#613A67",
  "#88D3E5",
];

export const MAXCOLOR = "red";

export const MINCOLOR = "green";

export const tableProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  // { name: "count", inputType: "number", ref: "columns", category: "Data" },
  {
    name: "columns",
    inputType: "listDropsRefColumns",
    category: "Data",
  },
  { name: "rowHeight", inputType: "number", category: "Customs" },
  // { name: "heightFactor", inputType: "number", category: "Customs" },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  {
    name: "headerFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "headerFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
  { name: "dataFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "dataFontWeight", inputType: "number", unit: "", category: "Fonts" },
];

export const pieProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  // { name: "xFontSize", inputType: "number", unit: "px", category: "Fonts" },
  // { name: "xFontWeight", inputType: "number", unit: "", category: "Fonts" },
  { name: "yFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "yFontWeight", inputType: "number", unit: "", category: "Fonts" },
  {
    name: "tooltipFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "tooltipFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
  {
    name: "X_Axis",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  // {
  //   name: "Y_Axis",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "columns",
  //   category: "Data",
  // },
  {
    name: "Y_Axis",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  // {
  //   name: "operationType",
  //   inputType: "select",
  //   dataType: "list",
  //   data: ["Count", "Sum", "Average"],
  //   category: "Data",
  // },
  {
    name: "tooltips",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "expressions",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "addExpressions",
    inputType: "expressionButton",
    category: "Data",
  },
  { name: "outerRadius", inputType: "number", category: "Customs" },
  { name: "innerRadius", inputType: "number", category: "Customs" },
  { name: "cx", inputType: "number", unit: "%", category: "Customs" },
  { name: "cy", inputType: "number", unit: "%", category: "Customs" },
  { name: "isTooltip", inputType: "toggle", category: "Customs" },
  { name: "isLegend", inputType: "toggle", category: "Customs" },
  { name: "isLabel", inputType: "toggle", category: "Customs" },
  { name: "count", inputType: "number", category: "Data" },
  {
    name: "Colors",
    inputType: "listtext",
    data: COLORS,
    category: "Colors",
  },
];

export const gaugeProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  {
    name: "Y_Axis",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  // {
  //   name: "label",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "columns",
  //   category: "Data",
  // },
  // {
  //   name: "value",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "columns",
  //   category: "Data",
  // },
  { name: "unit", inputType: "text", category: "Data" },
  // {
  //   name: "operationType",
  //   inputType: "select",
  //   dataType: "list",
  //   data: ["Count", "Sum", "Average"],
  //   category: "Data",
  // },
  { name: "min", inputType: "number", category: "Customs" },
  { name: "max", inputType: "number", category: "Customs" },
  { name: "threshold", inputType: "number", unit: "%", category: "Customs" },
  // { name: "cx", inputType: "number", unit: "%", category: "Customs" },
  // { name: "cy", inputType: "number", unit: "%", category: "Customs" },
];

export const barProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  // { name: "count", inputType: "number", ref: "datakeys", category: "Data" },
  {
    name: "X_Axis",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  {
    name: "Y_Axis",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "tooltips",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "expressions",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "addExpressions",
    inputType: "expressionButton",
    category: "Data",
  },
  { name: "max", inputType: "number", unit: "", category: "Data" },
  { name: "min", inputType: "number", unit: "", category: "Data" },
  { name: "xFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "xFontWeight", inputType: "number", unit: "", category: "Fonts" },
  { name: "yFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "yFontWeight", inputType: "number", unit: "", category: "Fonts" },
  {
    name: "tooltipFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "tooltipFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
  // {
  //   name: "legendFontSize",
  //   inputType: "number",
  //   unit: "px",
  //   category: "Fonts",
  // },
  // {
  //   name: "legendFontWeight",
  //   inputType: "number",
  //   unit: "px",
  //   category: "Fonts",
  // },
  // { name: "value", inputType: "select", dataType: "ref", ref: "columns" },
  // {
  //   name: "operationType",
  //   inputType: "select",
  //   dataType: "list",
  //   data: ["Count", "Sum", "Average"],
  //   category: "Data",
  // },
  // { name: "cx", inputType: "number", unit: "%" },
  // { name: "cy", inputType: "number", unit: "%" },
  { name: "isTooltip", inputType: "toggle", category: "Customs" },
  { name: "isLegend", inputType: "toggle", category: "Customs" },
  { name: "isLabel", inputType: "toggle", category: "Customs" },
  { name: "name", inputType: "text", category: "Customs" },
  {
    name: "Colors",
    inputType: "listtext",
    data: COLORS,
    category: "Colors",
  },
];

export const timelineProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  // { name: "count", inputType: "number", ref: "datakeys" },
  {
    name: "label",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  {
    name: "start",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  {
    name: "end",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  {
    name: "category",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  // {
  //   name: "datakeys",
  //   inputType: "listDropsRefColumns",
  //   category: "Data",
  // },
  // { name: "value", inputType: "select", dataType: "ref", ref: "columns" },
  // {
  //   name: "operationType",
  //   inputType: "select",
  //   dataType: "list",
  //   data: ["Count", "Sum", "Average"],
  //   category: "Data",
  // },
  // { name: "cx", inputType: "number", unit: "%" },
  // { name: "cy", inputType: "number", unit: "%" },
  { name: "isTooltip", inputType: "toggle", category: "Customs" },
  { name: "isLegend", inputType: "toggle", category: "Customs" },
  { name: "isCurveSlicer", inputType: "toggle", category: "Customs" },
  { name: "barHeight", inputType: "number", category: "Customs" },
  {
    name: "Colors",
    inputType: "listtext",
    data: COLORS,
    category: "Colors",
  },
];

export const lineProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  { name: "xFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "xFontWeight", inputType: "number", unit: "", category: "Fonts" },
  { name: "yFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "yFontWeight", inputType: "number", unit: "", category: "Fonts" },
  {
    name: "tooltipFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "tooltipFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
  // { name: "count", inputType: "number", ref: "datakeys", category: "Data" },
  {
    name: "X_Axis",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  {
    name: "Y_Axis",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "tooltips",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "expressions",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "addExpressions",
    inputType: "expressionButton",
    category: "Data",
  },
  // { name: "value", inputType: "select", dataType: "ref", ref: "columns" },
  // {
  //   name: "operationType",
  //   inputType: "select",
  //   dataType: "list",
  //   data: ["Count", "Sum", "Average"],
  //   category: "Data",
  // },
  // { name: "cx", inputType: "number", unit: "%" },
  // { name: "cy", inputType: "number", unit: "%" },
  { name: "isTooltip", inputType: "toggle", category: "Customs" },
  { name: "isLegend", inputType: "toggle", category: "Customs" },
  { name: "isCurveSlicer", inputType: "toggle", category: "Customs" },
  {
    name: "Colors",
    inputType: "listtext",
    data: COLORS,
    category: "Colors",
  },
];

export const schedulerProps = [
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  { name: "xFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "xFontWeight", inputType: "number", unit: "", category: "Fonts" },
  { name: "yFontSize", inputType: "number", unit: "px", category: "Fonts" },
  { name: "yFontWeight", inputType: "number", unit: "", category: "Fonts" },
  // {
  //   name: "X_Axis",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "columns",
  //   category: "Data",
  // },
  // {
  //   name: "Y_Axis",
  //   inputType: "listDropsRefColumns",
  //   select: true,
  //   category: "Data",
  // },
  {
    name: "Title",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "Description",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "Location",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "StartTime",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "EndTime",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  // {
  //   name: "expressions",
  //   inputType: "listDropsRefColumns",
  //   select: true,
  //   category: "Data",
  // },
  // {
  //   name: "addExpressions",
  //   inputType: "expressionButton",
  //   category: "Data",
  // },
];

export const slicerProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  {
    name: "mainSlicer",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  // {
  //   name: "count",
  //   inputType: "number",
  //   ref: "subSlicers",
  //   category: "Data",
  // },
  {
    name: "subSlicers",
    inputType: "listDropsRefColumns",
    category: "Data",
  },
  // {
  //   name: "actions",
  //   inputType: "listDropsRefTables",
  //   category: "Data",
  // },
  {
    name: "slicerType",
    inputType: "select",
    dataType: "list",
    data: ["Checks", "Date"],
    category: "Data",
  },
  {
    name: "filterType",
    inputType: "select",
    dataType: "list",
    data: ["Intersection", "Union"],
    category: "Data",
  },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  {
    name: "headerFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "headerFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
  {
    name: "dataFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "dataFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
];

export const cardProps = [
  // {
  //   name: "table",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "Tables",
  //   category: "Data",
  // },
  // {
  //   name: "column",
  //   inputType: "select",
  //   dataType: "ref",
  //   ref: "columns",
  //   category: "Data",
  // },
  {
    name: "X_Axis",
    inputType: "select",
    dataType: "ref",
    ref: "columns",
    category: "Data",
  },
  {
    name: "Y_Axis",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "tooltips",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "expressions",
    inputType: "listDropsRefColumns",
    select: true,
    category: "Data",
  },
  {
    name: "addExpressions",
    inputType: "expressionButton",
    category: "Data",
  },
  { name: "width", unit: "%", inputType: "number", category: "Position" },
  { name: "height", unit: "%", inputType: "number", category: "Position" },
  { name: "top", unit: "%", inputType: "number", category: "Position" },
  { name: "left", unit: "%", inputType: "number", category: "Position" },
  {
    name: "headerFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "headerFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
  {
    name: "dataFontSize",
    inputType: "number",
    unit: "px",
    category: "Fonts",
  },
  {
    name: "dataFontWeight",
    inputType: "number",
    unit: "",
    category: "Fonts",
  },
  {
    name: "operationType",
    inputType: "select",
    dataType: "list",
    data: ["Count", "Sum", "Average", "First", "Last", "Min", "Max"],
    category: "Data",
  },
  {
    name: "Format",
    inputType: "select",
    dataType: "list",
    data: ["Normal", "en-US"],
    category: "Data",
  },
  { name: "text", inputType: "text", category: "Customs" },
];

export const tablesOptions = {
  // table: "EqsTools",
  width: "200px",
  count: 0,
  columns: [],
  rowHeight: 0,
  headerFontSize: "10",
  headerFontWeight: "500",
  dataFontSize: "10",
  dataFontWeight: "500",
  // heightFactor: 1.4,
  height: "200px",
  top: 0,
  left: 0,
  Type: "Table",
  props: tableProps,
};

export const pieOptions = {
  table: null,
  name: null,
  [`X_Axis`]: null,
  [`Y_Axis`]: [],
  tooltips: [],
  tooltipProps: [],
  expressions: [],
  count: 1000,
  width: "200px",
  height: "200px",
  // xFontSize: "10",
  // xFontWeight: "500",
  yFontSize: "10",
  yFontWeight: "500",
  tooltipFontSize: "10",
  tooltipFontWeight: "500",
  top: 0,
  left: 0,
  Type: "Graph",
  graphType: "Pie",
  operationType: "Count",
  outerRadius: 80,
  innerRadius: 0,
  cx: "50%",
  cy: "50%",
  isTooltip: true,
  isLegend: false,
  isLabel: false,
  props: pieProps,
  Colors: [...COLORS],
};

export const gaugeOptions = {
  table: null,
  name: null,
  label: null,
  Y_Axis: [],
  unit: "",
  threshold: 80,
  width: "200px",
  height: "200px",
  top: 0,
  left: 0,
  Type: "Graph",
  graphType: "Gauge",
  operationType: "Count",
  cx: "50%",
  cy: "70%",
  outerRadius: 80,
  min: 0,
  max: 100,
  props: gaugeProps,
};

export const barOptions = {
  table: null,
  name: null,
  [`X_Axis`]: null,
  xFontSize: "10",
  xFontWeight: "500",
  yFontSize: "10",
  yFontWeight: "500",
  tooltipFontSize: "10",
  tooltipFontWeight: "500",
  max: 300,
  min: 0,
  // legendFontSize: "10px",
  // legendFontWeight: "500",
  // count: 1,
  [`Y_Axis`]: [],
  tooltips: [],
  expressions: [],
  tooltipProps: [],
  width: "200px",
  height: "200px",
  top: 0,
  left: 0,
  Type: "Graph",
  graphType: "Bar",
  operationType: "Count",
  cx: "50%",
  cy: "50%",
  isTooltip: true,
  isLegend: false,
  isLabel: false,
  props: barProps,
  Colors: [...COLORS],
};

export const timelineOptions = {
  table: null,
  name: null,
  label: null,
  start: null,
  end: null,
  barHeight: 2500,
  category: null,
  count: 10,
  datakeys: ["value"],
  width: "200px",
  height: "200px",
  top: 0,
  left: 0,
  Type: "Graph",
  graphType: "Timeline",
  operationType: "Count",
  cx: "50%",
  cy: "50%",
  isTooltip: true,
  isLegend: false,
  isCurveSlicer: false,
  props: timelineProps,
  Colors: [...COLORS],
};

export const lineOptions = {
  table: null,
  name: null,
  [`X_Axis`]: null,
  [`Y_Axis`]: [],
  tooltips: [],
  tooltipProps: [],
  expressions: [],
  width: "200px",
  height: "200px",
  xFontSize: "10",
  xFontWeight: "500",
  yFontSize: "10",
  yFontWeight: "500",
  tooltipFontSize: "10",
  tooltipFontWeight: "500",
  top: 0,
  left: 0,
  Type: "Graph",
  graphType: "Line",
  operationType: "Count",
  cx: "50%",
  cy: "50%",
  isTooltip: true,
  isLegend: false,
  isCurveSlicer: false,
  props: lineProps,
  Colors: [...COLORS],
};

export const schedulerOptions = {
  name: null,
  Title: [],
  Description: [],
  Location: [],
  StartTime: [],
  EndTime: [],
  // expressions: [],
  width: "200px",
  height: "200px",
  xFontSize: "10",
  xFontWeight: "500",
  yFontSize: "10",
  yFontWeight: "500",
  top: 0,
  left: 0,
  Type: "Scheduler",
  props: schedulerProps,
};

export const slicerOptions = {
  table: null,
  name: null,
  width: "200px",
  height: "200px",
  headerFontSize: "10",
  headerFontWeight: "500",
  dataFontSize: "10",
  dataFontWeight: "500",
  top: 0,
  left: 0,
  Type: "Slicer",
  mainSlicer: null,
  count: 0,
  subSlicers: [],
  actions: [],
  slicerType: "Checks",
  props: slicerProps,
};

export const cardOptions = {
  table: null,
  name: null,
  width: "200px",
  height: "200px",
  headerFontSize: "10",
  headerFontWeight: "500",
  dataFontSize: "10",
  dataFontWeight: "500",
  top: 0,
  left: 0,
  Type: "Card",
  column: "",
  [`X_Axis`]: null,
  Y_Axis: [],
  tooltips: [],
  tooltipProps: [],
  expressions: [],
  operationType: "Sum",
  Format: "en-US",
  text: "",
  props: cardProps,
};

export const DBData = [
  {
    name: "EqsTools",
    Type: "Table",
    table: "EqsTools",
    pageCount: 7,
  },
  {
    name: "Maintenance",
    Type: "Graph",
    graphType: "Pie",
    table: "Maintenance",
    label: "Breakdown_Type",
    value: "Total_EURO",
    isCount: true,
    count: 10,
  },
];

export const regix = {
  int: /^[0-9]*$/,
  intEmpty: /^$|^[0-9]*$/,
  date: /^(?:\d{4}-\d{2}-\d{2})$/,
  dateEmty: /^$|^(?:\d{4}-\d{2}-\d{2})$/,
  dateTime:
    /^(?:\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(.\d{3})?|(?:\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{3})?Z))$/,
  dateTimeOrNull:
    /^(?:\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(.\d{3})?|(?:\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{3})?Z))$/,
  nvarChar255: /^[0-9a-zA-Z\#\s\/\-\_\.]{0,255}$/,
  nvarchar255Empty: /^$|^.{0,255}$/,
  decimal81: /^\d{1,7}(\.\d{1})?$/,
  decimal82: /^\d{1,7}(\.\d{2})?$/,
  text: /^[a-zA-Z0-9 :,"{}[\]]*$/,
};
