version: "3"
services:
  node-app:
    build: ./backend
    volumes:
      - ./backend:/app:ro
      - /home/mohamed/bauereg:/home/mohamed/bauereg
    env_file:
      - ./backend/.env
  web:
    container_name: frontend_bauer
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - node-app
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
